[package]
name = "ffzap"
version.workspace = true
edition.workspace = true
description.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
ffzap_core = { path = "../core" }
clap.workspace = true
