[package]
name = "ffzap-ui"
version.workspace = true
edition.workspace = true
description.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
ffzap-shared = { path = "../shared" } 